### ISSUE TITLE
ALA banner appears twice

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#58]
The banner message that is configured via the `alaAdmin` page is currently showing the banner message twice. 

![image](https://user-images.githubusercontent.com/532845/88493708-ef7b6500-cff5-11ea-94cc-6bf1be8e8bb8.png)

The banner appears to be hard-coded, as it is not using the value from the `/alaAdmin` page, which is the blue box below.

![image](https://user-images.githubusercontent.com/532845/88493810-7d575000-cff6-11ea-9a83-4903517e7bdc.png)

**Comment by brucehyslop** [comment]
The issue is that the taglib `<ala:systemMessage/>` is included in the views and also in the `ala-main` layout. 

We can remove it from the views that use a layout that also displays the system message, however since the layout is configurable it would be possible to use a layout that does not display the system message.

**Comment by nickdos** [comment]
Meant to leave [this comment](https://github.com/AtlasOfLivingAustralia/doi-service/pull/59#issuecomment-671710172) here.

**Comment by Rita-C** [comment]
Hi @brucehyslop, the double banner is still showing in Test, @nickdos and I tested this morning, can you take another look please?

**Comment by ansell** [comment]
I removed the "This is a test site" banner on doi-test:

https://github.com/AtlasOfLivingAustralia/ansible-inventories/blob/master/doi/doi-test#L12-L14

It was causing confusion about the two different banners that ala-admin-plugin adds:

https://github.com/AtlasOfLivingAustralia/ala-admin-plugin/blob/a87d87a3720c14f6f04fb9c5215cd9f4be571cd5/grails-app/taglib/au/org/ala/admin/SystemMessageTagLib.groovy#L8-L35

I also switched the default on ala-install so that it will default to production if it isn't otherwise configured, which matches our other "production by default" settings in ala-install:

https://github.com/AtlasOfLivingAustralia/ala-install/commit/62fab34d2b161f25302f19c4e764e659b17a9876

The original issue here with the grails templates where the ala-admin-plugin systemMessage was put in twice has been fixed.
