### ISSUE TITLE
Requirements for commonly used download data 

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/doi-service#95]
Slack notes from @peggynewman  - Although Downloads should be working.  We need to be able to make clear recommendations for “how do I download all the bird data”, or “how do I download all data for WA”

**Comment by mjwestgate** [comment]
Using the DOI service to provide pre-built, large downloads seems very sensible to me. My only question is how someone will know what DOI to use to get a pre-packaged download; I'd suggest that we develop a simple API so that users can see what downloads are available. Ideally this should be filterable by whatever facets are most relevant, obvious choices being:

- date (or just 'most recent' flag)
- taxon (all or a subset)
- location (depends on whether we support state-specific downloads or not)

**Update frequency**
I'm open to different updating frequencies for packaging new datasets. I think monthly is probably optimal; quarterly is ok, annual is too slow, weekly is too fast.

**Taxonomy**
What groups are supported is a little ambiguous, because the optimal choice is affected by what groups are taxonomically appropriate, the total number of groups, and the total records per group. I'd propose starting at Kingdom and working downward. The following gives 15 groups, for example:

- Kingdom Animalia  (101,442,051)
  - Phylum Chordata (90,516,120)
    - Class Aves (77,070,340)
      - Order Passeriformes (40,027,304)
      - Other Avian Orders (37,043,036)
    - Class Actinopterygii (4,612,293)
    - Class Mammalia (4,368,854)
    - Class Reptilia (1,680,801)
    - Class Amphibia  (1,493,666)
    - Other Chordate Classes (1,270,150)
  - Phylum Arthropoda (8,203,921)
  - Other Animal Phyla (2,722,010)
- Kingdom Plantae  (26,121,184)
- Kingdom Fungi  (2,291,981)
- Other Kingdoms (including obviously invalid ones: 1,507,906)

**Comment by shandiya** [comment]
I think spatial and taxonomic facets make the most sense to be starting with, and I agree about keeping them as separate downloads as per @mjwestgate's comment. Some additional spatial facets to consider if we are interested in expanding this down the track:

- forest and non-forest, based on the most updated forests layer indexed in the ALA
- protected areas (CAPAD)

**Comment by adam-collins** [comment]
related https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/85

**Comment by adam-collins** [comment]
Update from a few months ago.
1. Use AVRO's with Airflow to generate parquet files.
2. Use this DOI service to generate and/or update a DOI for each, as required.
3. Put the files somewhere as yet not defined.
5. Put a link to the location using downloads-plugin config. Replaces the existing link.

Since I have not heard anything, and this appears to have nothing to do with the doi-service, closing.
